### ISSUE TITLE
训练图像通道与效果

### ISSUE THREAD

**Issue by zhanglaplace** [610265158/face_landmark_pytorch#1]
你好，为什么不用3通道数据训练，而要用灰度图呢。
还有我这边迭代的loss大概也是4左右，用的300vw+300w。
但是实际测试的时候嘴巴的预测非常不准确。想知道怎么能够达到peppa-pig-face Demo的效果

**Comment by sudabai666** [comment]
你应该没有做样本均衡，代码中是把 balance 函数注释起来的，你要根据自己的数据，进行修改

**Comment by 610265158** [comment]
1.这个repo只是对tensorflow版本的一个再次实现，没有仔细的校对，难免有些疏漏。
好像数据平衡被我注释掉了，为什么呢？我为什么要注掉呢，我也不理解。。。。打开就好了。

我现在把balance 打开了，但愿没有什么bug  

2.RGB和grayscale  我觉得区别不会很大，恢复图在移动端可能会更方便些，也会稍快点

**Comment by zhanglaplace** [comment]
@610265158  我已经打开了balance了，整体的数据大约从20w增加到200w左右。自己测试demo的时候发现了其他的点其实还挺稳定的，就只有嘴部的点和下巴的点，容易整体往上偏移很多。
我在后续实验迭代看下。谢谢回复～

**Comment by 610265158** [comment]
可能哪里有bug了，嘴巴的点其实还好

**Comment by zhanglaplace** [comment]
> 可能哪里有bug了，嘴巴的点其实还好

没有bug，后续迭代了下是可以的。不过dateiter的size那儿需要设置为balance之后的才合理。效果很赞～

**Comment by 610265158** [comment]
ok, cool

**Comment by fire717** [comment]
打开后代码如下，tf版本也是这样，
```
def parse_file(self,im_root_path,ann_file):
        '''
        :return:
        '''
        logger.info("[x] Get dataset from {}".format(im_root_path))

        ann_info = data_info(im_root_path, ann_file)
        all_samples = ann_info.get_all_sample()
        self.raw_data_set_size=len(all_samples)
        balanced_samples = self.balance(all_samples)
        return balanced_samples
```

我在想，self.raw_data_set_size=len(all_samples)是否要改为self.raw_data_set_size=len(balanced_samples)
如果没理解错的话，len(all_samples)是原始数据的数量，len(balanced_samples)是平衡后（过采样）后的总数量，
而self.raw_data_set_size是用于计算一个epoch有多少iter的，举个例子，假如原始数据1000条，过采样后10000条，
但是self.raw_data_set_size取1000，假如batchsize=100，那么每10个iter就是一个epoch，
但是实际数据为10000条，你10个iter才训练1000个数据，根本不能算一个epoch
不知道我是否理解有误
欢迎交流

**Comment by Aodamiaomiao** [comment]
> 打开后代码如下，tf版本也是这样，
> 
> ```
> def parse_file(self,im_root_path,ann_file):
>         '''
>         :return:
>         '''
>         logger.info("[x] Get dataset from {}".format(im_root_path))
> 
>         ann_info = data_info(im_root_path, ann_file)
>         all_samples = ann_info.get_all_sample()
>         self.raw_data_set_size=len(all_samples)
>         balanced_samples = self.balance(all_samples)
>         return balanced_samples
> ```
> 
> 我在想，self.raw_data_set_size=len(all_samples)是否要改为self.raw_data_set_size=len(balanced_samples) 如果没理解错的话，len(all_samples)是原始数据的数量，len(balanced_samples)是平衡后（过采样）后的总数量， 而self.raw_data_set_size是用于计算一个epoch有多少iter的，举个例子，假如原始数据1000条，过采样后10000条， 但是self.raw_data_set_size取1000，假如batchsize=100，那么每10个iter就是一个epoch， 但是实际数据为10000条，你10个iter才训练1000个数据，根本不能算一个epoch 不知道我是否理解有误 欢迎交流

Yes, If u balance the dataset, then you should change self.raw_data_set_size by youself to let the dataloader to know how many samples need to be loades per epoch.
