### ISSUE TITLE
Got 'StopIteration' error when run 'train.py'

### ISSUE THREAD

**Issue by xunge** [610265158/face_landmark_pytorch#3]
When I run train.py, the first epoch can train sucessfully, but the "StopIteration" error appears at the beginning of the second epoch, at [lib/dataset/dataietr.py#91](https://github.com/610265158/face_landmark_pytorch/blob/481ecce361cb2bb67b7bbbb6e8cf50125840c7ed/lib/dataset/dataietr.py#L91) . How can I fix this problem?

What's more, I do not use the '300VW' dataset, does it matter? Thank you.

**Comment by xunge** [comment]
I have solve the problem by this issue[https://github.com/610265158/face_landmark/issues/34](https://github.com/610265158/face_landmark/issues/34), thanks for the great project!

**Comment by hxhh** [comment]
I have the same problem,can you tell me how to solve it? thks

**Comment by 610265158** [comment]
> I have the same problem,can you tell me how to solve it? thks

it is the tensorpack version problem here, switch to 0.9.9 or try to fix it with the new tensopack

**Comment by hxhh** [comment]
ok,thks
